[tool.briefcase]
project_name = "What The Hex?"
bundle = "site.rwhogg.whatthehex"
version = "0.2.0"
url = "https://github.com/rwhogg/what-the-hex"
license = "LGPL-2.1+"
author = 'Bob Wombat Hogg'
author_email = "wombat@rwhogg.site"

[tool.briefcase.app.game]
formal_name = "What The Hex"
description = "Hexagonal puzzle game"
icon = "game/resources/icon"
sources = ["game"]
requires = ["toga==0.3.0.dev16", "pygame==2.0.1"]
