[tool.briefcase]
project_name = "What The Hex?"
bundle = "site.rwhogg.whatthehex"
version = "0.2.0"
url = "https://github.com/rwhogg/what-the-hex"
license = "LGPL-2.1+"
author = 'Bob Wombat Hogg'
author_email = "wombat@rwhogg.site"

[tool.briefcase.app.game]
formal_name = "What The Hex"
description = "Hexagonal puzzle game"
icon = "game/resources/icon"
sources = ["game"]
requires = ["appdirs==1.4.4", "toga==0.3.0.dev16", "pygame==2.0.1"]

[tool.briefcase.app.game.windows]
requires = [
    "toga-winforms==0.3.0.dev16"
]
system_installer = true

[tool.briefcase.app.game.macOS]
requires = [
    "toga-cocoa==0.3.0.dev16"
]

[tool.briefcase.app.game.linux]
requires = [
    "toga-gtk==0.3.0.dev16"
]
# FIXME: there's definitely a lot of system requirements here, both from pygame/SDL and from toga
# Actually, not sure how pygame handles libraries on Linux. Hmm...

[tool.briefcase.app.game.android]
requires = [
    "toga-android==0.3.0.dev16"
]
