# FIXME change this to JSON
name: Docker Image CI

on:
    push:
        branches: [ trunk]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - 
            name: Build the Docker image
            run: docker build . --file Dockerfile --tag what-the-hex-build-container:latest
        -
            name: Build solutions
            run: docker exec what-the-hex-build-container:latest godot --build-solutions
