name: .NET

on:
    push:
        branches: [ trunk ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            -
                name: Unshallow
                run: git fetch --unshallow
            - 
                name: Setup .NET
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 5.0.x
            -
                name: Restore dependencies
                run: cd project && dotnet restore
            -
                name: Build
                run: cd project && dotnet build --no-restore
