{
    "name": "Python application",
    "on": {
        "push": {
            "branches": [
                "trunk"
            ]
        },
        "pull_request": {
            "branches": [
                "trunk"
            ]
        }
    },
    "jobs": {
        "build": {
            "runs-on": "ubuntu-20.04",
            "steps": [
                {
                    "uses": "actions/checkout@v2"
                },
                {
                    "name": "Install system dependencies",
                    "run": "sudo apt install libgirepository1.0-dev"
                },
                {
                    "name": "Set up Python 3.7",
                    "uses": "actions/setup-python@v2",
                    "with": {
                        "python-version": 3.7
                    }
                },
                {
                    "uses": "actions/setup-node@v2",
                    "with": {
                        "node-version": "14"
                    }
                },
                {
                    "name": "Install dependencies",
                    "run": "python -m pip install --upgrade pip\nbash ./script/bootstrap.sh\n"
                },
                {
                    "name": "Lint",
                    "run": "bash ./script/lint.sh"
                },
                {
                    "name": "Typecheck",
                    "run": "bash ./script/typecheck.sh"
                },
                {
                    "name": "Test",
                    "run": "bash ./script/test.sh"
                }
            ]
        }
    }
}
