name: Python application

on:
  push:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        bash ./script/bootstrap.sh
    - name: Lint
      run: bash ./scripts/lint.sh
    - name: Typecheck
      run: bash ./scripts/typecheck.sh
    - name: Test
      run: bash ./scripts/test.sh
